name: End to end

on:
  push:
    #branches: [ master ]
    branches: [ master, fix-unzipping-error ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Package jar with Gradle
        run: ./gradlew shadowJar
      - name: Validate dataset from -- MBTA
        run: java -jar application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT_cli.jar -u https://cdn.mbta.com/MBTA_GTFS.zip -i input.zip -e input -o output
      - name: Validate dataset from issue #399 --
        run: java -jar application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT_cli.jar -u http://www.mst.org/google/google_transit.zip -i input.zip -e input -o output
      - name: Validate dataset from issue #398 -- Orange County Transportation Authority
        run: java -jar application/cli-app/build/libs/gtfs-validator-v1.3.0-SNAPSHOT_cli.jar -u https://octa.net/current/google_transit.zip -i input.zip -e input -o output
