name: Update Credits upon creating PR

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  update-credits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - run: |
          echo "### Timestamp:" >> .github/credits.md
          echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> .github/credits.md
          echo "### Contributor:" >> .github/credits.md
          echo "${{ github.event.pull_request.user.login }}" >> .github/credits.md
          echo "#### PR Title:" >> .github/credits.md
          echo "${{ github.event.pull_request.title }}" >> .github/credits.md
          echo "########################################################################################x" >> .github/credits.md

          git add .github/credits.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update credits.md with contributor information"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
